name:                lambda
version:             0.1.0.0
github:              "sudo-rushil/lambda"
license:             MIT
author:              "Rushil Mallarapu"
maintainer:          "rushil.mallarapu@gmail.com"
copyright:           "Rushil Mallarapu"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/sudo-rushil/lambda#readme>

dependencies:
- base >= 4.7 && < 5
- array >= 0.5
- haskeline >= 0.7.1
- containers >= 0.4
- optparse-applicative >= 0.15
- mtl >= 2.2
- bytestring >= 0.10

library:
  source-dirs: src

executables:
  lambda:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -O3
    - -rtsopts
    - -with-rtsopts=-N
    - -optP-Wno-nonportable-include-path
    build-tools:
    - alex
    - happy
    default-extensions:
    - OverloadedStrings
    dependencies:
    - lambda
