{-|
Module      : Lambda.Parse
Description : Wrapper over the parser generated by Happy

License     : MIT
Maintainer  : Rushil Mallarapu
-}

module Lambda.Parse
    ( Hi(..)
    ) where


data Hi = Plus
    | Minus
    | Times
    | Divide
    | Equal
    | Less
    deriving (Eq, Ord, Show)
